FROM rust:1.89-alpine3.22 AS builder
WORKDIR /usr/src/my-app

COPY Cargo.toml Cargo.lock ./
COPY src ./src

RUN cargo build --release

FROM debian:bullseye-slim

COPY --from=builder /usr/src/my-app/target/release/crud_proj /usr/local/bin/crud_proj
CMD ["crud_proj"]