FROM rust:1.89-alpine3.22 AS builder
WORKDIR /usr/src/my-app

RUN apk add --no-cache musl-dev openssl-dev postgresql-dev

COPY Cargo.toml Cargo.lock ./
RUN cargo build --release --target x86_64-unknown-linux-musl
RUN rm src/*.rs

COPY src ./src
RUN touch src/main.rs
RUN cargo build --release --target x86_64-unknown-linux-musl

FROM alpine:3.22
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /usr/src/my-app/target/x86_64-unknown-linux-musl/release/crud_proj /usr/local/bin/crud_proj
CMD ["crud_proj"]